export const WORLD_ASSET_KEYS = Object.freeze({
  WORLD_BACKGROUND: "WORLD_BACKGROUND",
  WORLD_MAIN_LEVEL: "WORLD_MAIN_LEVEL",
  WORLD_COLLISION: "WORLD_COLLISION",
  // WORLD_FOREGROUND: "WORLD_FOREGROUND",
});

export const CHARACTER_ASSET_KEYS = Object.freeze({
  PLAYER: "PLAYER",
  NPC: "NPC",
});

export const DATA_ASSET_KEYS = Object.freeze({
  ANIMATIONS: "ANIMATIONS",
});
